---
title: "Aula 2"
output: html_document
---

```{r}
library(stats4)
library(tidyr)
library(psych)
library(ggplot2)
library(base)
library(utils)
library(mosaic)
```


```{r}

exemplo <- read.csv2("~/caminhao.csv")

bau <- subset(exemplo$Tempo, exemplo$Tipo == "bau")
lonado <- subset(exemplo$Tempo, exemplo$Tipo == "lonado")

str(exemplo)

summary(exemplo)

c <- describe(exemplo)

c$mean
c$sd

```
```{r}
# Função para limpar NA do final da variável
Limpar = function(a) {
  QuantNA <- sum(is.na(a))
  Quant <- length(a)
  QuantReal <- Quant - QuantNA
  a <- head(a, QuantReal)
  return(a)
  }

lonado <- Limpar(lonado)



```

```{r}


# Gráfico sequencial + Box Plot
SequencialBoxplot = function(a){
tamanho <- length(a)
x <- 1:tamanho
boxplot(a)
plot(a ~ x, type = "b")
par(mfrow=c(1,2))
boxplot(a)
plot(a ~ x, type = "b")
par(mfrow=c(1,1))
}

SequencialBoxplot(bau)
SequencialBoxplot(lonado)

boxplot(bau,lonado)

```

```{r}
#intervalo de confiança para média
t.test(alcool, conf.level = 0.95)
t.test(alcool, conf.level = 0.9)

# Grafico do intervalo de confiança
GraficoIntConf = function(a){
 c <- describe(a)
 xbarra <- c$mean
 variancia <- c$sd*c$sd
 tamanho <- length(a)

t.ic <- xbarra + qt(c(0.025, 0.975), df = tamanho-1) * sqrt(variancia/tamanho)

Osdados1 <- data.frame("nome_estimativa" = "estimativa1",
                    "media_estimada" = xbarra,
                    "limite_inferior" = t.ic[1],
                    "lim_superior" = t.ic[2]) 

ggplot(Osdados1,aes(x = nome_estimativa, y = media_estimada)) +
geom_point(color = "black",size = 3) +
geom_errorbar(aes(ymin = limite_inferior,ymax = lim_superior), color = "red")
}

GraficoIntConf(alcool)
```


```{r}
#Intervalo de confiança para Variancia
Intervalo_Var <- function(data, conf.level = 0.95) {
 df = length(data) - 1
 chilower = qchisq((1 - conf.level)/2, df)
 chiupper = qchisq((1 - conf.level)/2, df, lower.tail = FALSE)
 c <- describe(data)
 v = c$sd*c$sd
 c(df * v/chiupper, df * v/chilower)
}

Intervalo_Var(alcool, conf.level = 0.90)

```


```{r}
#Teste para igualdade de Variância
Bonett.Seier.test(bau,lonado)

leveneTest(exemplo$Tempo, exemplo$Tipo)

var.test(bau,lonado)

```

```{r}
t.test(bau, lonado, conf.level = 0.95, var.equal = FALSE)
````
```{r}
pedidos <- c(481, 455)
errados <- c(12, 18)

prop.test(errados, pedidos)
```